### PR TITLE
branch appengine, make gwu & example work on appengine. gofmt.

### PR DESCRIPTION
**Pull request by djadala**
hi, please create branch appengine.
see [Showcase](https://loba-1110.appspot.com/)
Regards,
Jamil Djadala

### CODE REVIEW

**Comment by icza** [comment]
Please note this project is for Gowut Public Releases only. Development takes place in the gowut.dev project:

https://github.com/icza/gowut.dev

**Comment by djadala** [comment]
ok, do you want new pull request against  gowut.dev ? ignoring go fmt, changes are small.
Regards

**Comment by icza** [comment]
I'd rather not have 2 branches, but I'd like to solve AppEngine support with build constraints, like:

// +build appengine

and

// +build !appengine

**Comment by icza** [comment]
Closing this pull request as development takes place in gowut.dev:
https://github.com/icza/gowut.dev

Result of Goftm is already committed here:
https://github.com/icza/gowut.dev/commit/679856f998ef2662134f02bb650aa209d4583e3a

**Pull request closed without merging**
