### PR TITLE
improve ID

### PR DESCRIPTION
**Pull request by jfcg**
- make ID uint64 to have consistent size on 32/64 platforms
- use hex representation, shorter
- add ID test

### CODE REVIEW

**Comment by icza** [comment]
This project is for public releases and for issue tracking of Gowut. Development takes place in the [gowut.dev](https://github.com/icza/gowut.dev) project.

**Comment by jfcg** [comment]
That is weird. Single project also allows you to have tags & releases. Why have two for the same thing?

**Comment by icza** [comment]
Because `go get` does not support fetching a release, it always fetches the tip of the default branch.

Also the dev project contains many additional files ("garbage") which are not needed to use gowut, they are only to aid the development.

A branch could be used though which would be a better solution, but for now, development takes place in gowut.dev.

**Comment by icza** [comment]
Closing this PR. Submit to gowut.dev if you want to.

**Pull request closed without merging**
